name: "Set Issue Label and Assignee"
on:
  issues:
    types: [opened]
  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v2.0.2
        with:
          title-or-body: "both"
          parameters: >
            [
            {"keywords":["UI", "design"],"labels":["UI", "design"],"assignees":["habibokumus"]}
            ]
      - uses: Naturalclar/issue-action@v2.0.2
        with:
          title-or-body: "both"
          parameters: >
            [
            {"keywords":["backend", "feature", "API"],"labels":["backend", "feature"],"assignees":["fers4t"]}
            ]