name: Project - Opened Issues

on:
  issues:
    types: [opened]

env:
  SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to New Issues to Triage Project
    steps:
    - name: Process bug issues
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      if: github.event.action == 'closed'
      env:
        SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/users/fers4t/projects/5
        GITHUB_PROJECT_COLUMN_NAME: 'Done'
    